name: Auto PR test

on:
  pull_request:
    branches:
      - main
      - dev
  workflow_dispatch:

jobs:
  run_test:
    name: run test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        dotnet-version: ['6.0', '7.0', '8.0', '9.0']
    
    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ matrix.dotnet-version }}.x
          
      - name: Test net${{ matrix.dotnet-version }}
        run: dotnet test test/EfCorePlus.Test --framework net${{ matrix.dotnet-version }}
