name: Auto PR test

on:
  pull_request:
    branches:
      - main
      - dev
  workflow_dispatch:

jobs:
  run_test:
    name: run test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        dotnet: ['6', '7', '8', '9']  # 添加你需要的 .NET 版本
      fail-fast: false  # 如果一个作业失败，是否停止其他作业

    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ matrix.dotnet }}.0.x
          
      - name: Test  ${{ matrix.dotnet-version }}
        run: dotnet test test/EfCorePlus.Test -p:TargetFramework=net${{ matrix.dotnet }}.0
