name: Auto PR test

on:
  pull_request:
    branches:
      - main
      - dev
  workflow_dispatch:

jobs:
  run_test:
    name: run test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        dotnet-version: ['3.1.x','6.0.x', '7.0.x', '8.0.x', '9.0.x']  # 添加你需要的 .NET 版本
      fail-fast: false  # 如果一个作业失败，是否停止其他作业

    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET SDK ${{ matrix.dotnet-version }}
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ matrix.dotnet-version }}
      
      - name: Install dependencies
        run: dotnet restore test/EfCorePlus.Test
        
      - name: Build
        run: dotnet build test/EfCorePlus.Test --configuration Release --no-restore
        
      - name: Test
        run: dotnet test test/EfCorePlus.Test --no-restore --verbosity normal
