name: Create Release Draft

on:
  push:
    branches:
      - release 

jobs:
  draft-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Generate Release Notes
        id: release_notes
        uses: release-drafter/release-drafter@v5
        with:
          name: "Release ${{ github.ref_name }}"
          tag_name: "v${{ github.ref_name }}"
          prerelease: false
          draft: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install setuptools wheel

      - name: Create source distribution
        run: |
          python setup.py sdist

      - name: Upload source distribution
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.release_notes.outputs.upload_url }}
          asset_path: ./dist/*.tar.gz
          asset_name: source-code.tar.gz
          asset_content_type: application/gzip