name: Create Release Draft

on:
  push:
    branches:
      - main  # 你可以根据需要更改分支名称

jobs:
  create_release_draft:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Create source code archive
        run: |
          mkdir -p dist
          tar -czf dist/source-code.tar.gz .

      - name: Create Release Draft
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref_name }}
          release_name: Release ${{ github.ref_name }}
          draft: true
          prerelease: false

      - name: Upload Source Code Archive
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./dist/source-code.tar.gz
          asset_name: source-code.tar.gz
          asset_content_type: application/gzip